/**
 * iQOO Creator Studio - Video & Multi-track Timeline Engine
 */

export class TimelineEngine {
  constructor(canvasElement) {
    this.canvas = canvasElement;
    this.ctx = canvasElement.getContext('2d');
    
    // Timeline state
    this.duration = 18.0; // seconds
    this.currentTime = 2.4; // current playhead position
    this.isPlaying = false;
    this.fps = 30;
    this.activeClipIndex = 0;
    this.inPoint = 0;
    this.outPoint = this.duration;

    // Color Grading Parameters
    this.colorParams = {
      exposure: 0,    // -100 to 100
      contrast: 10,   // -100 to 100
      saturation: 15, // -100 to 100
      temperature: 5, // -100 to 100 (warm/cool)
      tint: 0         // -100 to 100 (magenta/green)
    };

    // Default Multi-Clip Sequence
    this.clips = [
      { id: 'clip-1', name: '01_Cyber_Neon.mp4', start: 0.0, end: 4.5, color: '#2563EB', theme: 'neon' },
      { id: 'clip-2', name: '02_Night_Drive.mp4', start: 4.5, end: 10.2, color: '#7C3AED', theme: 'drive' },
      { id: 'clip-3', name: '03_Drone_City.mp4', start: 10.2, end: 18.0, color: '#DB2777', theme: 'city' }
    ];

    // Beat Markers (generated by BeatSnap AI)
    this.beatMarkers = [1.2, 2.4, 4.5, 6.8, 8.0, 10.2, 12.5, 14.8, 16.0];

    // Audio Track
    this.audioTrack = {
      name: 'iQOO_HyperBeat_128BPM.wav',
      duration: 18.0,
      bpm: 128
    };

    // Animation & rendering loop
    this.lastFrameTime = performance.now();
    this.listeners = [];

    this.initCanvas();
    this.startRenderLoop();
  }

  initCanvas() {
    this.canvas.width = 1920;
    this.canvas.height = 1080;
  }

  subscribe(callback) {
    this.listeners.push(callback);
  }

  notify(event, payload) {
    this.listeners.forEach(cb => cb(event, payload, this));
  }

  play() {
    this.isPlaying = true;
    this.lastFrameTime = performance.now();
    this.notify('playState', { isPlaying: true });
  }

  pause() {
    this.isPlaying = false;
    this.notify('playState', { isPlaying: false });
  }

  togglePlay() {
    if (this.isPlaying) this.pause();
    else this.play();
  }

  seek(time) {
    this.currentTime = Math.max(0, Math.min(this.duration, time));
    this.updateActiveClip();
    this.notify('seek', { time: this.currentTime });
  }

  stepFrames(frameCount) {
    const timeDelta = frameCount * (1.0 / this.fps);
    this.seek(this.currentTime + timeDelta);
  }

  updateActiveClip() {
    const idx = this.clips.findIndex(c => this.currentTime >= c.start && this.currentTime < c.end);
    if (idx !== -1) {
      this.activeClipIndex = idx;
    }
  }

  splitAtPlayhead() {
    const t = this.currentTime;
    const clipIdx = this.clips.findIndex(c => t > c.start + 0.2 && t < c.end - 0.2);
    if (clipIdx === -1) return false;

    const original = this.clips[clipIdx];
    const newClip1 = { ...original, id: `clip-${Date.now()}-a`, end: t };
    const newClip2 = { 
      ...original, 
      id: `clip-${Date.now()}-b`, 
      name: `${original.name.replace('.mp4', '')}_cut.mp4`, 
      start: t, 
      color: '#EA580C' 
    };

    this.clips.splice(clipIdx, 1, newClip1, newClip2);
    this.notify('timelineChanged', { clips: this.clips });
    return true;
  }

  rippleDeleteCurrentClip() {
    if (this.clips.length <= 1) return;
    const removed = this.clips.splice(this.activeClipIndex, 1)[0];
    const gap = removed.end - removed.start;

    // Shift subsequent clips
    for (let i = this.activeClipIndex; i < this.clips.length; i++) {
      this.clips[i].start -= gap;
      this.clips[i].end -= gap;
    }

    this.duration -= gap;
    this.currentTime = Math.min(this.currentTime, this.duration);
    this.updateActiveClip();
    this.notify('timelineChanged', { clips: this.clips });
  }

  applyColorGrade(paramName, value) {
    if (this.colorParams[paramName] !== undefined) {
      this.colorParams[paramName] = value;
      this.notify('colorGraded', { params: this.colorParams });
    }
  }

  resetColorGrade() {
    this.colorParams = { exposure: 0, contrast: 10, saturation: 15, temperature: 5, tint: 0 };
    this.notify('colorGraded', { params: this.colorParams });
  }

  applyBeatSnapCuts(beatTimestamps) {
    this.beatMarkers = beatTimestamps;
    const newClips = [];
    const colors = ['#2563EB', '#7C3AED', '#DB2777', '#059669', '#D97706', '#0284C7'];

    let prevTime = 0;
    beatTimestamps.forEach((bt, idx) => {
      if (bt <= prevTime + 0.5) return;
      newClips.push({
        id: `beatsnap-clip-${idx}`,
        name: `Scene_${idx + 1}_BeatSync.mp4`,
        start: prevTime,
        end: bt,
        color: colors[idx % colors.length],
        theme: idx % 3 === 0 ? 'neon' : (idx % 3 === 1 ? 'drive' : 'city')
      });
      prevTime = bt;
    });

    if (prevTime < this.duration) {
      newClips.push({
        id: `beatsnap-clip-end`,
        name: `Scene_Outro_BeatSync.mp4`,
        start: prevTime,
        end: this.duration,
        color: '#4F46E5',
        theme: 'neon'
      });
    }

    this.clips = newClips;
    this.notify('timelineChanged', { clips: this.clips, beatMarkers: this.beatMarkers });
  }

  startRenderLoop() {
    const loop = (now) => {
      const delta = (now - this.lastFrameTime) / 1000;
      this.lastFrameTime = now;

      if (this.isPlaying) {
        this.currentTime += delta;
        if (this.currentTime >= this.duration) {
          this.currentTime = 0;
        }
        this.updateActiveClip();
        this.notify('timeUpdate', { time: this.currentTime });
      }

      this.renderFrame();
      requestAnimationFrame(loop);
    };
    requestAnimationFrame(loop);
  }

  renderFrame() {
    const { ctx, canvas } = this;
    const w = canvas.width;
    const h = canvas.height;
    const t = this.currentTime;

    // Clear canvas
    ctx.fillStyle = '#05070D';
    ctx.fillRect(0, 0, w, h);

    // Get active clip theme
    const activeClip = this.clips[this.activeClipIndex] || this.clips[0];
    const theme = activeClip ? activeClip.theme : 'neon';

    ctx.save();

    // 1. Apply Real-time Color Grading Matrix
    const exposureVal = 1 + (this.colorParams.exposure / 100);
    const contrastVal = 100 + this.colorParams.contrast;
    const satVal = 100 + this.colorParams.saturation;
    const hueVal = this.colorParams.tint * 1.5;
    
    ctx.filter = `brightness(${exposureVal}) contrast(${contrastVal}%) saturate(${satVal}%) hue-rotate(${hueVal}deg)`;

    // 2. Procedural High-Dynamic Cinema Scene Rendering
    if (theme === 'neon') {
      this.drawCyberNeonScene(ctx, w, h, t);
    } else if (theme === 'drive') {
      this.drawNightDriveScene(ctx, w, h, t);
    } else {
      this.drawCitySkylineScene(ctx, w, h, t);
    }

    // 3. Color Temperature Tint overlay
    if (this.colorParams.temperature !== 0) {
      ctx.restore();
      ctx.save();
      if (this.colorParams.temperature > 0) {
        // Warm Orange
        ctx.fillStyle = `rgba(255, 140, 0, ${this.colorParams.temperature / 400})`;
      } else {
        // Cool Blue
        ctx.fillStyle = `rgba(0, 150, 255, ${Math.abs(this.colorParams.temperature) / 400})`;
      }
      ctx.fillRect(0, 0, w, h);
    }

    ctx.restore();

    // 4. Studio Watermark & 4K Cinema Framing Guide
    this.drawCinemaOverlay(ctx, w, h, t, activeClip);
  }

  drawCyberNeonScene(ctx, w, h, t) {
    const grad = ctx.createLinearGradient(0, 0, w, h);
    grad.addColorStop(0, '#0F172A');
    grad.addColorStop(0.5, '#1E1B4B');
    grad.addColorStop(1, '#020617');
    ctx.fillStyle = grad;
    ctx.fillRect(0, 0, w, h);

    // Glowing Perspective Grid
    ctx.strokeStyle = 'rgba(255, 230, 0, 0.25)';
    ctx.lineWidth = 2;
    const horizon = h * 0.65;
    const vpX = w * 0.5 + Math.sin(t * 1.5) * 60;

    // Horizon line
    ctx.beginPath();
    ctx.moveTo(0, horizon);
    ctx.lineTo(w, horizon);
    ctx.stroke();

    // Vanishing perspective rays
    for (let x = -w * 0.5; x <= w * 1.5; x += 120) {
      ctx.beginPath();
      ctx.moveTo(vpX, horizon);
      ctx.lineTo(x, h);
      ctx.stroke();
    }

    // Horizontal moving grid lines
    const offset = (t * 80) % 50;
    for (let y = horizon; y <= h; y += (y - horizon + 10) * 0.25 + 5) {
      ctx.beginPath();
      ctx.moveTo(0, y + offset);
      ctx.lineTo(w, y + offset);
      ctx.stroke();
    }

    // Glowing Cyber Sun / Geometric Element
    const sunY = horizon - 160;
    const sunGrad = ctx.createRadialGradient(vpX, sunY, 10, vpX, sunY, 160);
    sunGrad.addColorStop(0, '#FFE600');
    sunGrad.addColorStop(0.5, '#FF4A00');
    sunGrad.addColorStop(1, 'transparent');
    ctx.fillStyle = sunGrad;
    ctx.beginPath();
    ctx.arc(vpX, sunY, 140, 0, Math.PI * 2);
    ctx.fill();

    // Action Text in Frame
    ctx.fillStyle = '#FFFFFF';
    ctx.font = '900 64px Outfit, sans-serif';
    ctx.textAlign = 'center';
    ctx.fillText('iQOO 13 // SNAPDRAGON 8 ELITE', w / 2, horizon + 160);
  }

  drawNightDriveScene(ctx, w, h, t) {
    ctx.fillStyle = '#09090B';
    ctx.fillRect(0, 0, w, h);

    // Fast light streaks
    const count = 18;
    for (let i = 0; i < count; i++) {
      const y = h * 0.2 + (i * (h * 0.6 / count));
      const speed = 600 + (i * 80);
      const x = ((t * speed + i * 240) % (w + 400)) - 200;
      const length = 180 + Math.sin(i + t) * 60;

      const isTailLight = i % 2 === 0;
      ctx.fillStyle = isTailLight ? 'rgba(255, 40, 40, 0.8)' : 'rgba(0, 240, 255, 0.8)';
      ctx.shadowColor = isTailLight ? '#FF0000' : '#00F0FF';
      ctx.shadowBlur = 15;

      ctx.beginPath();
      ctx.roundRect(x, y, length, 8, 4);
      ctx.fill();
      ctx.shadowBlur = 0;
    }

    ctx.fillStyle = '#E4E4E7';
    ctx.font = '800 56px Outfit, sans-serif';
    ctx.textAlign = 'center';
    ctx.fillText('TACTILE CREATOR DECK', w / 2, h * 0.5);
  }

  drawCitySkylineScene(ctx, w, h, t) {
    const skyGrad = ctx.createLinearGradient(0, 0, 0, h);
    skyGrad.addColorStop(0, '#1E293B');
    skyGrad.addColorStop(0.7, '#0F172A');
    skyGrad.addColorStop(1, '#020617');
    ctx.fillStyle = skyGrad;
    ctx.fillRect(0, 0, w, h);

    // City Silhouette Buildings
    const bldgs = 16;
    const bWidth = w / bldgs;
    for (let i = 0; i < bldgs; i++) {
      const bHeight = 250 + Math.sin(i * 99) * 180;
      ctx.fillStyle = '#090D16';
      ctx.fillRect(i * bWidth, h - bHeight, bWidth - 4, bHeight);

      // Windows
      ctx.fillStyle = (i + Math.floor(t * 4)) % 3 === 0 ? '#FFE600' : 'rgba(255,255,255,0.2)';
      for (let wy = h - bHeight + 20; wy < h - 20; wy += 25) {
        for (let wx = i * bWidth + 10; wx < (i + 1) * bWidth - 14; wx += 20) {
          ctx.fillRect(wx, wy, 8, 12);
        }
      }
    }

    ctx.fillStyle = '#00FF88';
    ctx.font = '800 52px Outfit, sans-serif';
    ctx.textAlign = 'center';
    ctx.fillText('.IQOO EDIT RECIPE // MOVE THE EDIT', w / 2, 220);
  }

  drawCinemaOverlay(ctx, w, h, t, activeClip) {
    // Top & Bottom Cinematic Letterbox bar lines
    ctx.strokeStyle = 'rgba(255, 255, 255, 0.15)';
    ctx.lineWidth = 1;
    ctx.strokeRect(60, 40, w - 120, h - 80);

    // Crosshairs
    const cx = w / 2;
    const cy = h / 2;
    ctx.strokeStyle = 'rgba(255, 230, 0, 0.4)';
    ctx.beginPath();
    ctx.moveTo(cx - 15, cy); ctx.lineTo(cx + 15, cy);
    ctx.moveTo(cx, cy - 15); ctx.lineTo(cx, cy + 15);
    ctx.stroke();

    // Bottom Badge
    ctx.fillStyle = 'rgba(0, 0, 0, 0.6)';
    ctx.fillRect(80, h - 90, 360, 36);
    ctx.fillStyle = '#FFE600';
    ctx.font = '700 16px "JetBrains Mono", monospace';
    ctx.textAlign = 'left';
    ctx.fillText(`4K 60FPS | ${activeClip ? activeClip.name : 'MASTER'}`, 95, h - 66);
  }

  getTimecodeString(timeSec) {
    const mins = Math.floor(timeSec / 60);
    const secs = Math.floor(timeSec % 60);
    const frames = Math.floor((timeSec % 1) * this.fps);
    return `${String(mins).padStart(2, '0')}:${String(secs).padStart(2, '0')}:${String(frames).padStart(2, '0')}`;
  }
}
